version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x

  pre_build:
    commands:
      - npm install yarn --location=global
      - yarn install

  build:
    commands:
      - yarn lint
      - cd packages/api
      - make all
